{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pathfinder-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.hosts.ui }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ui
            port:
              number: {{ .Values.ui.port }}
  - host: {{ .Values.ingress.hosts.api }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: {{ .Values.api.port }}
  - host: {{ .Values.ingress.hosts.jaeger }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jaeger
            port:
              number: {{ .Values.jaeger.port }}
  {{- if .Values.ingress.hosts.otel }}
  - host: {{ .Values.ingress.hosts.otel }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: otel-collector
            port:
              number: {{ .Values.otelCollector.httpPort }}
  {{- end }}
{{- end }}
